// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfO4VGw_lTq6Z6Vy86N6obIK5rg7D0eeQ',
    appId: '1:207334463555:web:fdf8db28e644d5d769dcf6',
    messagingSenderId: '207334463555',
    projectId: 'shopexx-49bc9',
    authDomain: 'shopexx-49bc9.firebaseapp.com',
    databaseURL: 'https://shopexx-49bc9-default-rtdb.firebaseio.com',
    storageBucket: 'shopexx-49bc9.appspot.com',
    measurementId: 'G-VRK2JYLQX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSuDehPy9y6NHIQny_De4iGfZ74JLLkJQ',
    appId: '1:207334463555:android:666b4505a583507369dcf6',
    messagingSenderId: '207334463555',
    projectId: 'shopexx-49bc9',
    databaseURL: 'https://shopexx-49bc9-default-rtdb.firebaseio.com',
    storageBucket: 'shopexx-49bc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC455orzQ_04HDF4Glko35ZarkDk443URE',
    appId: '1:207334463555:ios:07f2962aeede48d769dcf6',
    messagingSenderId: '207334463555',
    projectId: 'shopexx-49bc9',
    databaseURL: 'https://shopexx-49bc9-default-rtdb.firebaseio.com',
    storageBucket: 'shopexx-49bc9.appspot.com',
    iosClientId: '207334463555-jqsnt591qip215otd5qj3igg2shppg1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopexx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC455orzQ_04HDF4Glko35ZarkDk443URE',
    appId: '1:207334463555:ios:07f2962aeede48d769dcf6',
    messagingSenderId: '207334463555',
    projectId: 'shopexx-49bc9',
    databaseURL: 'https://shopexx-49bc9-default-rtdb.firebaseio.com',
    storageBucket: 'shopexx-49bc9.appspot.com',
    iosClientId: '207334463555-jqsnt591qip215otd5qj3igg2shppg1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopexx',
  );
}
